### ISSUE TITLE
feat/Auction-detail

### ISSUE THREAD

**Issue by Oh-Donghan** [UsedAuction/front-end#1]
---
name: Feature request
about: 새로운 기능을 구현할 때
title: 'feat: 중고 경매 상세 페이지 구현'
labels: 'feature'
assignees: '동한'

---

## 📌 이슈 내용
경매 상세 페이지를 구현
- 경매 물품의 상세 정보 (예: 이미지, 이름, 설명, 현재 가격, 입찰자 리스트 등)
- 경매 시간 (종료 시간)
- 입찰 기능 (입찰 금액 입력 및 제출)
- QnA 기능 (사용자 QnA 입력 및 표시)
- 기타 관련 정보 및 기능

<br>

## 📝 To-do
- [ ] 경매 물품 상세 정보 섹션 구현
- [ ] 경매 시간 표시 섹션 구현
- [ ] 입찰 기능 구현
- [ ] 입찰 금액 입력 필드 및 제출 버튼
- [ ] 입찰 로직 및 유효성 검사
- [ ] QnA 기능 구현
- [ ] QnA 입력 필드 및 제출 버튼
- [ ] QnA 리스트 표시
- [ ] 기타 관련 정보 및 기능 구현
