### ISSUE TITLE
[FEAT]: 목데이터 생성 (MSW)

### ISSUE THREAD

**Issue by Oh-Donghan** [UsedAuction/front-end#22]
## 📌 이슈 내용
> 목 데이터를 사용한 네트워크 요청의 테스트 환경을 구성하기 위해 MSW를 사용한 목데이터 구현 필요.
API 엔드포인트와 함께 헤더, 파라미터 등을 처리할 수 있도록 설정하여 실제 서버 배포 전 테스트를 원활하게 진행할 수 있게 함.

<br>

## 📝 To-do
- [x] /api/transactions/sales 엔드포인트를 위한 목 핸들러 작성
- [x] Header 및 Query Param을 이용한 데이터 처리 구현
- [x] axios 요청 시 MSW를 통해 목데이터 반환 확인
- [x] 페이지네이션, 검색, 정렬 관련 목데이터 구현
